env: "XMagicalTrajectory-v0"
device: "cuda"
env_cfg:
  early_success: False
  task_agnostic: False
  reward_type: "lcs_dense2"
  # path to file with trajectory ids
  trajectories: "datasets/xmagical/dataset_train_ids.npy"
  trajectories_dataset: "datasets/xmagical/dataset.pkl"
  give_traj_id: False
  embodiment: 'Shortstick'
  max_trajectory_skip_steps: 999
  fixed_max_ep_len: 200

exp_cfg:
  algo: ppo
  seed: 0
  n_envs: 4

  gae_lambda: 0.97
  target_kl: 0.1
  log_std_scale: -0.5
  pi_lr: 3e-4
  vf_lr: 3e-4

  accumulate_grads: False
  #ppo configs
  epochs: 50000 #200
  critic_warmup_epochs: 0
  update_iters: 3
  steps_per_epoch: 20000
  batch_size: 1024
  eval_freq: 5
  eval_save_video: True
  max_ep_len: 200

  dapg: False

logging_cfg:
  exp_name: transformer_xmagical
  wandb: False
  tensorboard: True
  log_freq: 1

model_cfg:
  type: "TranslationTransformer"
  pretrained_actor_weights: None
  pretrained_critic_weights: None

  state_dims: 16
  act_dims: 2
  teacher_dims: 8

  max_time_steps: 1024
  # below should also be merged into dataset_cfgs
  max_student_length: 300
  max_teacher_length: 32
  trajectory_sample_skip_steps: 6
  # equivalent to positional embeddings
  # timestep_embeddings: True
  timestep_embeddings: False
  # whether to include past student actions into the student stack frames fed into transformer
  use_past_actions: False
  # whether to use layer normalization after the initial embedding layers of student/teacher states and student actions
  embed_layer_norm: True

  # translation model specific configs
  stack_size: 3
  state_embedding_hidden_sizes: (32,)
  state_embedding_activation: 'relu'
  final_mlp_hidden_sizes: (128, 128)
  final_mlp_activation: 'relu'
  
  final_mlp_action_pred_activation: 'tanh'
  final_mlp_state_pred_activation: 'tanh'

  encoder_config:
    type: "state"

  # gpt2 specific https://huggingface.co/docs/transformers/model_doc/gpt2#transformers.GPT2Config
  transformer_config:
    n_head: 2
    n_layer: 4
    activation_function: 'gelu_new'
    resid_pdrop: 0.1 
    embd_pdrop: 0.1
    attn_pdrop: 0.1